// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYlDPLLS07a-moIZ7u5Sx5IYlCJPkRqE',
    appId: '1:626700965286:web:e171c99d46ac39b5742b67',
    messagingSenderId: '626700965286',
    projectId: 'needauth-f873e',
    authDomain: 'needauth-f873e.firebaseapp.com',
    storageBucket: 'needauth-f873e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYIlf_RBmL-waxSqt0bDq2GNnqzNKoDE',
    appId: '1:626700965286:android:3a37c8d5c6f31b89742b67',
    messagingSenderId: '626700965286',
    projectId: 'needauth-f873e',
    storageBucket: 'needauth-f873e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMSSqoROVNaMCPrF_BbjFcVSY0wXwMbT8',
    appId: '1:626700965286:ios:318f1cf0e386b1eb742b67',
    messagingSenderId: '626700965286',
    projectId: 'needauth-f873e',
    storageBucket: 'needauth-f873e.firebasestorage.app',
    iosBundleId: 'com.example.needMobileApp',
  );
}
